# Dependencies
markdown:         kramdown
highlighter:      rouge  # previously pygments

# Permalinks
permalink:        pretty

# Setup
title:            Esteban Zacharzewski
tagline:
url:
paginate:         1
baseurl:          https://stzr1123.github.io/
author:
  name:           Esteban Zacharzewski
  url:
  email:

# Custom vars
version:
github:
  repo:

# This is the list of pages to incldue in the header of the website.
pages_list:       {'About':'/about','Entries':'/entries','More':'/more'}
